[tool.poetry]
name = "graph_ml"
version = "0.1"
description = ""
authors = ["Ashutosh Tiwari <checkashu@gmail.com>"]
readme = "README.md"
packages = [{include = "graph_ml"}]
classifiers = [
    "Environment :: GPU :: NVIDIA CUDA",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[tool.poetry.dependencies]
python = "3.10.12"
pandas = "*"
seaborn = "^0.13.0"
numpy = "1.24.3"
scikit-learn = "1.2.2"
kaggle = "*"
ipython = "*"
joblib = "^1.3.2"
psutil = "^5.9.5"
notebook = "6.4.12"
wandb = "^0.15.12"
pyarrow = "^13.0.0"
nvitop = "^1.3.1"
urllib3 = "1.26.11"
ipywidgets = "^8.1.1"
pickleshare = "^0.7.5"
torch = "^2.1.2"
torchaudio = "^2.1.2"
torchvision = "^0.16.2"
pytorch-lightning = "^2.1.3"
codeium-jupyter = "^1.1.21"
jupyter-contrib-nbextensions = "^0.7.0"
traittypes = "^0.2.1"
traitlets = "5.9.0"
transformers = "^4.37.2"
datasets = "^2.17.1"
evaluate = "^0.4.1"
accelerate = "^0.27.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


