name: Release

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos"]

    steps:
      - name: Checkout GraphML
        id: checkout_graphml
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: Get short SHA
        id: get_short_sha
        uses: benjlevesque/short-sha@v2.2

      - name: Install Python
        id: install_python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        id: install_poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        id: install_dependencies
        run: poetry install --with main

      - name: Build release
        id: build_release
        run: poetry build -f wheel

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
